# Generated by Django 3.2.5 on 2021-07-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_post',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='author_product',
            new_name='author',
        ),
    ]
