# Generated by Django 3.2.5 on 2021-07-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-title']},
        ),
    ]
